#ifndef __EMODEL__
#define __EMODEL__

#include <string>

class EModel
{
public:
   static std::string None;
   static std::string All;
   static std::string Bmw1E81;
   static std::string Bmw1E82;
   static std::string Bmw1E87;
   static std::string Bmw1E88;
   static std::string Bmw1F20;
   static std::string Bmw1F21;
   static std::string Bmw1F40;
   static std::string Bmw1F52;
   static std::string Bmw2F22;
   static std::string Bmw2F23;
   static std::string Bmw2F45;
   static std::string Bmw2F46;
   static std::string Bmw2F44;
   static std::string Bmw2G42;
   static std::string Bmw3E30;
   static std::string Bmw3E36;
   static std::string Bmw3E46;
   static std::string Bmw3E90;
   static std::string Bmw3E92;
   static std::string Bmw3F30;
   static std::string Bmw3G20;
   static std::string Bmw4F32;
   static std::string Bmw4F33;
   static std::string Bmw4F36;
   static std::string Bmw4G22;
   static std::string Bmw4G23;
   static std::string Bmw4G26;
   static std::string Bmw5E34;
   static std::string Bmw5E39;
   static std::string Bmw5E60;
   static std::string Bmw5E61;
   static std::string Bmw5F10;
   static std::string Bmw5F11;
   static std::string Bmw5F07;
   static std::string Bmw5F18;
   static std::string Bmw5G30;
   static std::string Bmw5G31;
   static std::string Bmw5G38;
   static std::string Bmw6E63;
   static std::string Bmw6E64;
   static std::string Bmw6F06;
   static std::string Bmw6F12;
   static std::string Bmw6F13;
   static std::string Bmw6G32;
   static std::string Bmw7E38;
   static std::string Bmw7E65;
   static std::string Bmw7E66;
   static std::string Bmw7E67;
   static std::string Bmw7F68;
   static std::string Bmw7F01;
   static std::string Bmw7F02;
   static std::string Bmw7F03;
   static std::string Bmw7F04;
   static std::string Bmw7G11;
   static std::string Bmw7G12;
   static std::string BmwX1E84;
   static std::string BmwX1F48;
   static std::string BmwX3E83;
   static std::string BmwX3F25;
   static std::string BmwX3G01;
   static std::string BmwX4F26;
   static std::string BmwX4G02;
   static std::string BmwX5E53;
   static std::string BmwX5E70;
   static std::string BmwX5F15;
   static std::string BmwX5G05;
   static std::string BmwX6E71;
   static std::string BmwX6F16;
   static std::string BmwX6G06;
   static std::string BmwX7G07;
   static std::string BmwZ4E85;
   static std::string BmwZ4E86;
   static std::string BmwZ4E89;
   static std::string BmwZ4G29;
   static std::string MercedesBenz190W201;
   static std::string MercedesBenzAW168;
   static std::string MercedesBenzAW169;
   static std::string MercedesBenzAW176;
   static std::string MercedesBenzAW177;
   static std::string MercedesBenzBW245;
   static std::string MercedesBenzBW246;
   static std::string MercedesBenzBW247;
   static std::string MercedesBencCW202;
   static std::string MercedesBencCW203;
   static std::string MercedesBencCW204;
   static std::string MercedesBencCW205;
   static std::string MercedesBencCW206;
   static std::string MercedesBencEW124;
   static std::string MercedesBencEW210;
   static std::string MercedesBencEW211;
   static std::string MercedesBencEW212;
   static std::string MercedesBencEC207;
   static std::string MercedesBencEA207;
   static std::string MercedesBencEW213;
   static std::string MercedesBencSW140;
   static std::string MercedesBencSW220;
   static std::string MercedesBencSW221;
   static std::string MercedesBencSW222;
   static std::string MercedesBencSW223;
   static std::string MercedesBencCLC140;
   static std::string MercedesBencCLC215;
   static std::string MercedesBencCLC216;
   static std::string MercedesBencCLAC117;
   static std::string MercedesBencCLKC208;
   static std::string MercedesBencCLKA208;
   static std::string MercedesBencCLKC209;
   static std::string MercedesBencCLKA209;
   static std::string MercedesBencCLSC219;
   static std::string MercedesBencCLSC256;
   static std::string MercedesBencMLW163;
   static std::string MercedesBencMLW164;
   static std::string MercedesBencMLW166;
   static std::string MercedesBencMLW167;
   static std::string MercedesBencGW463;
   static std::string MercedesBencGLX164;
   static std::string MercedesBencGLX166;
   static std::string MercedesBencGLAX156;
   static std::string MercedesBencGLAH247;
   static std::string MercedesBencGLCX253;
   static std::string MercedesBencGLCC253;
   static std::string MercedesBencGLEV167;
   static std::string MercedesBencGLKX204;
   static std::string MercedesBencGLSX167;
   static std::string MercedesBencRW251;
   static std::string MercedesBencSLR230;
   static std::string MercedesBencSLR231;
   static std::string MercedesBencSLKR170;
   static std::string MercedesBencSLKR171;
   static std::string MercedesBencSLKR172;
   static std::string MercedesBencVW638;
   static std::string MercedesBencVW639;
   static std::string MercedesBencVW447;
   static std::string MercedesBencSprinterW901;
   static std::string MercedesBencSprinterW905;
   static std::string MercedesBencSprinternNCV3;
   static std::string MercedesBencVaneoW414;
   static std::string MercedesBencViano;
   static std::string MercedesBencVito;
   static std::string AudiA38L;
   static std::string AudiA38P;
   static std::string AudiA38V;
   static std::string AudiA38Y;
   static std::string AudiA4B5;
   static std::string AudiA4B6;
   static std::string AudiA4B7;
   static std::string AudiA4B8;
   static std::string AudiA4B9;
   static std::string AudiA58T;
   static std::string AudiA5F5;
   static std::string AudiA6C5;
   static std::string AudiA6C6;
   static std::string AudiA6C7;
   static std::string AudiA6C8;
   static std::string AudiA7G4;
   static std::string AudiA74K;
   static std::string AudiA8D2;
   static std::string AudiA8D3;
   static std::string AudiA8D4;
   static std::string AudiA8D5;
   static std::string AudiQ58R;
   static std::string AudiQ5FY;
   static std::string AudiQ74L;
   static std::string AudiQ74M;
   static std::string AudiTT8N;
   static std::string AudiTT8J;
   static std::string AudiTT8S;
   static std::string PorscheCayenne1;
   static std::string PorscheCayenne2;
   static std::string PorscheCayenne3;
   static std::string PorscheMacan1;
   static std::string PorschePanamera1;
   static std::string PorschePanamera2;
   static std::string LexusCT1;
   static std::string LexusIS1;
   static std::string LexusIS2;
   static std::string LexusIS3;
   static std::string LexusES4;
   static std::string LexusES5;
   static std::string LexusES6;
   static std::string LexusES7;
   static std::string LexusGS2;
   static std::string LexusGS3;
   static std::string LexusGS4;
   static std::string LexusLS4;
   static std::string LexusLS5;
   static std::string LexusNX1;
   static std::string LexusNX2;
   static std::string LexusRX1;
   static std::string LexusRX2;
   static std::string LexusRX3;
   static std::string LexusRX4;
   static std::string LexusGX1;
   static std::string LexusGX2;
   static std::string LexusLX2;
   static std::string LexusLX3;
   static std::string InfinitiEX1J50;
   static std::string InfinitiJX1;
   static std::string InfinitiFX1S50;
   static std::string InfinitiFX2S51;
   static std::string InfinitiG3;
   static std::string InfinitiG4;
   static std::string InfinitiM3;
   static std::string InfinitiM4;
   static std::string InfinitiQ3;
   static std::string InfinitiQX4;
   static std::string InfinitiQX501;
   static std::string InfinitiQX502;
   static std::string InfinitiQX561;
   static std::string InfinitiQX562;
   static std::string InfinitiQX601;
   static std::string InfinitiQX70;
   static std::string InfinitiQX801;
   static std::string InfinitiQX802;
   static std::string ToyotaAlphard1;
   static std::string ToyotaAlphard2;
   static std::string ToyotaAlphard3;
   static std::string ToyotaAltezza;
   static std::string ToyotaAvalon3;
   static std::string ToyotaAvalon4;
   static std::string ToyotaAvalon5;
   static std::string ToyotaAvensis2;
   static std::string ToyotaAvensis3;
   static std::string ToyotaBelta;
   static std::string ToyotaBlade1E150;
   static std::string ToyotaCHR1;
   static std::string ToyotaCamryXV40;
   static std::string ToyotaCamryXV50;
   static std::string ToyotaCamryXV70;
   static std::string ToyotaCorollaE140;
   static std::string ToyotaCorollaE160;
   static std::string ToyotaCorollaE210;
   static std::string ToyotaEstima2;
   static std::string ToyotaEstima3;
   static std::string ToyotaFJCruiser;
   static std::string ToyotaFortuner1;
   static std::string ToyotaFortuner2;
   static std::string ToyotaHarrierXU10;
   static std::string ToyotaHarrierXU30;
   static std::string ToyotaHarrierXU60;
   static std::string ToyotaHighlanderU20;
   static std::string ToyotaHighlanderU40;
   static std::string ToyotaHighlanderU50;
   static std::string ToyotaHighlanderU70;
   static std::string ToyotaHilux6;
   static std::string ToyotaHilux7;
   static std::string ToyotaHilux8;
   static std::string ToyotaIpsumM10;
   static std::string ToyotaIpsumM20;
   static std::string ToyotaIst1;
   static std::string ToyotaIst2;
   static std::string ToyotaLandCruiser100;
   static std::string ToyotaLandCruiser200;
   static std::string ToyotaLandCruiser300;
   static std::string ToyotaLandCruiserPrado120;
   static std::string ToyotaLandCruiserPrado150;
   static std::string ToyotaNoahR60;
   static std::string ToyotaNoahR70;
   static std::string ToyotaNoahR80;
   static std::string ToyotaPasso1;
   static std::string ToyotaPasso2;
   static std::string ToyotaPasso3;
   static std::string ToyotaPriusXW10;
   static std::string ToyotaPriusXW20;
   static std::string ToyotaPriusXW30;
   static std::string ToyotaPriusXW50;
   static std::string ToyotaRAV4XA10;
   static std::string ToyotaRAV4XA20;
   static std::string ToyotaRAV4XA30;
   static std::string ToyotaRAV4CA40;
   static std::string ToyotaRAV4XA50;
   static std::string ToyotaSequoia1;
   static std::string ToyotaSequoia2;
   static std::string ToyotaSienna1;
   static std::string ToyotaSienna2;
   static std::string ToyotaSienna3;
   static std::string ToyotaSienna4;
   static std::string ToyotaTacoma1;
   static std::string ToyotaTacoma2;
   static std::string ToyotaTacoma3;
   static std::string ToyotaTundra1;
   static std::string ToyotaTundra2;
   static std::string ToyotaVellfire1;
   static std::string ToyotaVellfire2;
   static std::string ToyotaVitzP10;
   static std::string ToyotaVitzXP90;
   static std::string ToyotaVitzXP130;
   static std::string ToyotaVoxyR60;
   static std::string ToyotaVoxyR70;
   static std::string ToyotaVoxyR80;
   static std::string ToyotaYaris;
   static std::string NissanAlmeraN16;
   static std::string NissanAlmeraG15;
   static std::string NissanAltimaL32;
   static std::string NissanAltimaL33;
   static std::string NissanAltimaL34;
   static std::string NissanArmada1;
   static std::string NissanArmada2;
   static std::string NissanBluebird;
   static std::string NissanCubeZ10;
   static std::string NissanCubeZ11;
   static std::string NissanCubeZ12;
   static std::string NissanElgrandE50;
   static std::string NissanElgrandE51;
   static std::string NissanElgrandE52;
   static std::string NissanFrontier;
   static std::string NissanFuga1;
   static std::string NissanFuga2;
   static std::string NissanJuke1;
   static std::string NissanJuke2;
   static std::string NissanKicks1;
   static std::string NissanLatioN71;
   static std::string NissanLeafZE0;
   static std::string NissanLeafZE1;
   static std::string NissanMarchK12;
   static std::string NissanMarchK13;
   static std::string NissanMaximaA34;
   static std::string NissanMaximaA35;
   static std::string NissanMaximaA36;
   static std::string NissanMicra3;
   static std::string NissanMicra4;
   static std::string NissanMicra5;
   static std::string NissanMuranoZ50;
   static std::string NissanMuranoZ51;
   static std::string NissanMuranoZ52;
   static std::string NissanNote1;
   static std::string NissanNote2;
   static std::string NissanPathfinder3;
   static std::string NissanPathfinder4;
   static std::string NissanPathfinder5;
   static std::string NissanPatrolY61;
   static std::string NissanPatrolY62;
   static std::string NissanPresage1;
   static std::string NissanPresage2;
   static std::string NissanQashqai1;
   static std::string NissanQashqai2;
   static std::string NissanQashqai3;
   static std::string NissanQuest3;
   static std::string NissanQuest4;
   static std::string NissanRogue1;
   static std::string NissanRogue2;
   static std::string NissanRogue3;
   static std::string NissanSentraB16;
   static std::string NissanSentraB17;
   static std::string NissanSentraB18;
   static std::string NissanSerenaC24;
   static std::string NissanSerenaC25;
   static std::string NissanSerenaC26;
   static std::string NissanSerenaC27;
   static std::string NissanSkylineR34;
   static std::string NissanSkylineV35;
   static std::string NissanSkylineV36;
   static std::string NissanSkylineV37;
   static std::string NissanSunnyN16;
   static std::string NissanSunnyB10;
   static std::string NissanTeana1;
   static std::string NissanTeana2;
   static std::string NissanTeana3;
   static std::string NissanTerrano2;
   static std::string NissanTerrano3;
   static std::string NissanTiida1;
   static std::string NissanTiida2;
   static std::string NissanVersa1;
   static std::string NissanVersa2;
   static std::string NissanVersa3;
   static std::string NissanXTrail1;
   static std::string NissanXTrail2;
   static std::string NissanXTrail3;
   static std::string NissanXTerra1;
   static std::string NissanXTerra2;
   static std::string Nissan350Z;
   static std::string FordEdge1;
   static std::string FordEdge2;
   static std::string FordEscape1;
   static std::string FordEscape2;
   static std::string FordEscape3;
   static std::string FordEscape4;
   static std::string FordExplorer1;
   static std::string FordExplorer2;
   static std::string FordExplorer3;
   static std::string FordExplorer4;
   static std::string FordExplorer5;
   static std::string FordExplorer6;
   static std::string FordF15010;
   static std::string FordF15011;
   static std::string FordF15012;
   static std::string FordF15013;
   static std::string FordFiestaMK6;
   static std::string FordFiestaMK7;
   static std::string FordFocus1;
   static std::string FordFocus2;
   static std::string FordFocus3;
   static std::string FordFocus4;
   static std::string FordFusion2;
   static std::string FordTaurus6;
   static std::string FordTransit;
   static std::string FordMustang4;
   static std::string FordMustang5;
   static std::string FordMustang6;
   static std::string ChevroletAvalanche1;
   static std::string ChevroletAvalanche2;
   static std::string ChevroletAveo1;
   static std::string ChevroletAveo2;
   static std::string ChevroletAveo3;
   static std::string ChevroletCaptiva1;
   static std::string ChevroletCruze1;
   static std::string ChevroletCruze2;
   static std::string ChevroletEpicaV250;
   static std::string ChevroletEquinox1;
   static std::string ChevroletEquinox2;
   static std::string ChevroletEquinox3;
   static std::string ChevroletMalibu7;
   static std::string ChevroletMalibu8;
   static std::string ChevroletMalibu9;
   static std::string ChevroletNiva;
   static std::string ChevroletTahoe2;
   static std::string ChevroletTahoe3;
   static std::string ChevroletTahoe4;
   static std::string ChevroletTahoe5;
   static std::string ChevroletTrailBlazer1;
   static std::string ChevroletTrailBlazer2;
   static std::string ChevroletTrailBlazer3;
   static std::string ChevroletVolt1;
   static std::string ChevroletVolt2;
   static std::string ChevroletCamaro5;
   static std::string ChevroletCamaro6;
   static std::string ChevroletCorvette;
   static std::string VolkswagenBeetleA4;
   static std::string VolkswagenBeetleA5;
   static std::string VolkswagenBora1998;
   static std::string VolkswagenBora4;
   static std::string VolkswagenCaddy2;
   static std::string VolkswagenCaddy3;
   static std::string VolkswagenCaddy4;
   static std::string VolkswagenCaddy5;
   static std::string VolkswagenCrafter;
   static std::string VolkswagenGolf2;
   static std::string VolkswagenGolf3;
   static std::string VolkswagenGolf4;
   static std::string VolkswagenGolf5;
   static std::string VolkswagenGolf6;
   static std::string VolkswagenGolf7;
   static std::string VolkswagenGolf8;
   static std::string VolkswagenJetta3;
   static std::string VolkswagenJetta4;
   static std::string VolkswagenJetta5;
   static std::string VolkswagenJetta6;
   static std::string VolkswagenJetta7;
   static std::string VolkswagenPassatB5;
   static std::string VolkswagenPassatB6;
   static std::string VolkswagenPassatB7;
   static std::string VolkswagenPassatB8;
   static std::string VolkswagenPassatCC1;
   static std::string VolkswagenPolo3;
   static std::string VolkswagenPolo4;
   static std::string VolkswagenPolo5;
   static std::string VolkswagenPolo6;
   static std::string VolkswagenRoutan;
   static std::string VolkswagenTiguan1;
   static std::string VolkswagenTiguan2;
   static std::string VolkswagenTouareg1;
   static std::string VolkswagenTouareg2;
   static std::string VolkswagenTouareg3;
   static std::string VolkswagenTouran1;
   static std::string VolkswagenTouran2;
   static std::string VolkswagenTouran3;
   static std::string VolkswagenTransporterT4;
   static std::string VolkswagenTransporterT5;
   static std::string VolkswagenTransporterT6;
   static std::string VolkswagenVento;
   static std::string OpelAstraF;
   static std::string OpelAstraG;
   static std::string OpelAstraH;
   static std::string OpelAstraJ;
   static std::string OpelAstraK;
   static std::string OpelComboC;
   static std::string OpelComboD;
   static std::string OpelComboE;
   static std::string OpelComboPCMA;
   static std::string OpelCorsaA;
   static std::string OpelCorsaB;
   static std::string OpelCorsaC;
   static std::string OpelCorsaD;
   static std::string OpelCorsaE;
   static std::string OpelCorsaF;
   static std::string OpelFronteraA;
   static std::string OpelFronteraB;
   static std::string OpelInsignia1;
   static std::string OpelInsignia2;
   static std::string OpelMerivaA;
   static std::string OpelMerivaB;
   static std::string OpelOmegaA;
   static std::string OpelOmegaB;
   static std::string OpelSignum;
   static std::string OpelSintra;
   static std::string OpelVectraA;
   static std::string OpelVectraB;
   static std::string OpelVectraC;
   static std::string OpelZafiraA;
   static std::string OpelZafiraB;
   static std::string OpelZafiraC;
   static std::string MitsubishiAirtrek;
   static std::string MitsubishiChariot2;
   static std::string MitsubishiChariot3;
   static std::string MitsubishiColtZ30;
   static std::string MitsubishiGalant8;
   static std::string MitsubishiGalant9;
   static std::string MitsubishiGrandis;
   static std::string MitsubishiLancer9;
   static std::string MitsubishiLancer10;
   static std::string MitsubishiMontero3;
   static std::string MitsubishiMontero4;
   static std::string MitsubishiOutlander1;
   static std::string MitsubishiOutlander2;
   static std::string MitsubishiOutlander3;
   static std::string MitsubishiPajero2;
   static std::string MitsubishiPajero3;
   static std::string MitsubishiPajero4;
   static std::string KIACadenza1;
   static std::string KIACadenza2;
   static std::string KIACerato1;
   static std::string KIACerato2;
   static std::string KIACerato3;
   static std::string KIAForte1;
   static std::string KIAForte2;
   static std::string KIAForte3;
   static std::string KIAK51;
   static std::string KIAK52;
   static std::string KIAK53;
   static std::string KIAOptima2;
   static std::string KIAOptima3;
   static std::string KIAOptima4;
   static std::string KIARio2;
   static std::string KIARio3;
   static std::string KIARio4;
   static std::string KIASedona1;
   static std::string KIASedona2;
   static std::string KIASedona3;
   static std::string KIASorento1;
   static std::string KIASorento2;
   static std::string KIASorento3;
   static std::string KIASorento4;
   static std::string KIASportage2;
   static std::string KIASportage3;
   static std::string KIASportage4;
   static std::string HyundaiAccent2;
   static std::string HyundaiAccent3;
   static std::string HyundaiAccent4;
   static std::string HyundaiAccent5;
   static std::string HyundaiCreta1;
   static std::string HyundaiCreta2;
   static std::string HyundaiElantra4;
   static std::string HyundaiElantra5;
   static std::string HyundaiElantra6;
   static std::string HyundaiElantra7;
   static std::string HyundaiGenesis1;
   static std::string HyundaiGenesis2;
   static std::string HyundaiGenesisCoupe1;
   static std::string HyundaiIX351;
   static std::string HyundaiKona1;
   static std::string HyundaiSantaFe1;
   static std::string HyundaiSantaFe2;
   static std::string HyundaiSantaFe3;
   static std::string HyundaiSantaFe4;
   static std::string HyundaiSolaris1;
   static std::string HyundaiSolaris2;
   static std::string HyundaiSonata5;
   static std::string HyundaiSonata6;
   static std::string HyundaiSonata7;
   static std::string HyundaiSonata8;
   static std::string HyundaiTucson1;
   static std::string HyundaiTucson2;
   static std::string HyundaiTucson3;
   static std::string HyundaiTucson4;
   static std::string HyundaiVeloster1;
   static std::string HyundaiVeloster2;
   static std::string HondaAccord7;
   static std::string HondaAccord8;
   static std::string HondaAccord9;
   static std::string HondaAccord10;
   static std::string HondaCivic7;
   static std::string HondaCivic8;
   static std::string HondaCivic9;
   static std::string HondaCivic10;
   static std::string HondaCivic11;
   static std::string HondaCRV1;
   static std::string HondaCRV2;
   static std::string HondaCRV3;
   static std::string HondaCRV4;
   static std::string HondaCRV5;
   static std::string HondaCrosstour1;
   static std::string HondaElysion1;
   static std::string HondaFit1;
   static std::string HondaFit2;
   static std::string HondaFit3;
   static std::string HondaHRV1;
   static std::string HondaHRV2;
   static std::string HondaOdyssey3;
   static std::string HondaOdyssey4;
   static std::string HondaOdyssey5;
   static std::string HondaOdyssey6;
   static std::string HondaPilot1;
   static std::string HondaPilot2;
   static std::string HondaPilot3;
   static std::string HondaRidgeline1;
   static std::string HondaRidgeline2;
   static std::string HondaStepwgn2;
   static std::string HondaStepwgn3;
   static std::string HondaStepwgn4;
   static std::string HondaStepwgn5;
   static std::string MazdaAtenza1;
   static std::string MazdaAtenza2;
   static std::string MazdaAtenza3;
   static std::string MazdaCX31;
   static std::string MazdaCX51;
   static std::string MazdaCX52;
   static std::string MazdaCX71;
   static std::string MazdaCX91;
   static std::string MazdaCX92;
   static std::string MazdaDemio1;
   static std::string MazdaDemio2;
   static std::string MazdaDemio3;
   static std::string MazdaDemio4;
   static std::string MazdaMPV2;
   static std::string MazdaMPV3;
   static std::string MazdaRX8;
   static std::string MazdaTribute1;
   static std::string MazdaTribute2;
   static std::string Mazda32;
   static std::string Mazda33;
   static std::string Mazda34;
   static std::string Mazda51;
   static std::string Mazda52;
   static std::string Mazda61;
   static std::string Mazda62;
   static std::string Mazda63;

   static std::string ToString(const std::string& model)
    {
       if (EModel::Bmw1E81 == model) return "E81";
       if (EModel::Bmw1E82 == model) return "E82";
       if (EModel::Bmw1E87 == model) return "E87";
       if (EModel::Bmw1E88 == model) return "E88";
       if (EModel::Bmw1F20 == model) return "F20";
       if (EModel::Bmw1F21 == model) return "F21";
       if (EModel::Bmw1F40 == model) return "F40";
       if (EModel::Bmw1F52 == model) return "F52";
       if (EModel::Bmw2F22 == model) return "F22";
       if (EModel::Bmw2F23 == model) return "F23";
       if (EModel::Bmw2F45 == model) return "F45";
       if (EModel::Bmw2F46 == model) return "F46";
       if (EModel::Bmw2F44 == model) return "F44";
       if (EModel::Bmw2G42 == model) return "G42";
       if (EModel::Bmw3E30 == model) return "E30";
       if (EModel::Bmw3E36 == model) return "E36";
       if (EModel::Bmw3E46 == model) return "E46";
       if (EModel::Bmw3E90 == model) return "E90";
       if (EModel::Bmw3E92 == model) return "E92";
       if (EModel::Bmw3F30 == model) return "F30";
       if (EModel::Bmw3G20 == model) return "G20";
       if (EModel::Bmw4F32 == model) return "F32";
       if (EModel::Bmw4F33 == model) return "F33";
       if (EModel::Bmw4F36 == model) return "F36";
       if (EModel::Bmw4G22 == model) return "G22";
       if (EModel::Bmw4G23 == model) return "G23";
       if (EModel::Bmw4G26 == model) return "G26";
       if (EModel::Bmw5E34 == model) return "E34";
       if (EModel::Bmw5E39 == model) return "E39";
       if (EModel::Bmw5E60 == model) return "E60";
       if (EModel::Bmw5E61 == model) return "E61";
       if (EModel::Bmw5F10 == model) return "F10";
       if (EModel::Bmw5F11 == model) return "F11";
       if (EModel::Bmw5F07 == model) return "F07";
       if (EModel::Bmw5F18 == model) return "F18";
       if (EModel::Bmw5G30 == model) return "G30";
       if (EModel::Bmw5G31 == model) return "G31";
       if (EModel::Bmw5G38 == model) return "G38";
       if (EModel::Bmw6E63 == model) return "E63";
       if (EModel::Bmw6E64 == model) return "E64";
       if (EModel::Bmw6F06 == model) return "F06";
       if (EModel::Bmw6F12 == model) return "F12";
       if (EModel::Bmw6F13 == model) return "F13";
       if (EModel::Bmw6G32 == model) return "G32";
       if (EModel::Bmw7E38 == model) return "E38";
       if (EModel::Bmw7E65 == model) return "E65";
       if (EModel::Bmw7E66 == model) return "E66";
       if (EModel::Bmw7E67 == model) return "E67";
       if (EModel::Bmw7F68 == model) return "F68";
       if (EModel::Bmw7F01 == model) return "F01";
       if (EModel::Bmw7F02 == model) return "F02";
       if (EModel::Bmw7F03 == model) return "F03";
       if (EModel::Bmw7F04 == model) return "F04";
       if (EModel::Bmw7G11 == model) return "G11";
       if (EModel::Bmw7G12 == model) return "G12";
       if (EModel::BmwX1E84 == model) return "E84";
       if (EModel::BmwX1F48 == model) return "F48";
       if (EModel::BmwX3E83 == model) return "E83";
       if (EModel::BmwX3F25 == model) return "F25";
       if (EModel::BmwX3G01 == model) return "G01";
       if (EModel::BmwX4F26 == model) return "F26";
       if (EModel::BmwX4G02 == model) return "G02";
       if (EModel::BmwX5E53 == model) return "E53";
       if (EModel::BmwX5E70 == model) return "E70";
       if (EModel::BmwX5F15 == model) return "F15";
       if (EModel::BmwX5G05 == model) return "G05";
       if (EModel::BmwX6E71 == model) return "E71";
       if (EModel::BmwX6F16 == model) return "F16";
       if (EModel::BmwX6G06 == model) return "G06";
       if (EModel::BmwX7G07 == model) return "G07";
       if (EModel::BmwZ4E85 == model) return "E85";
       if (EModel::BmwZ4E86 == model) return "E86";
       if (EModel::BmwZ4E89 == model) return "E89";
       if (EModel::BmwZ4G29 == model) return "G29";
       if (EModel::MercedesBenz190W201 == model) return "W201";
       if (EModel::MercedesBenzAW168 == model) return "W168";
       if (EModel::MercedesBenzAW169 == model) return "W169";
       if (EModel::MercedesBenzAW176 == model) return "W176";
       if (EModel::MercedesBenzAW177 == model) return "W177";
       if (EModel::MercedesBenzBW245 == model) return "W245";
       if (EModel::MercedesBenzBW246 == model) return "W246";
       if (EModel::MercedesBenzBW247 == model) return "W247";
       if (EModel::MercedesBencCW202 == model) return "W202";
       if (EModel::MercedesBencCW203 == model) return "W203";
       if (EModel::MercedesBencCW204 == model) return "W204";
       if (EModel::MercedesBencCW205 == model) return "W205";
       if (EModel::MercedesBencCW206 == model) return "W206";
       if (EModel::MercedesBencEW124 == model) return "W124";
       if (EModel::MercedesBencEW210 == model) return "W210";
       if (EModel::MercedesBencEW211 == model) return "W211";
       if (EModel::MercedesBencEW212 == model) return "W212";
       if (EModel::MercedesBencEC207 == model) return "W207";
       if (EModel::MercedesBencEA207 == model) return "W207";
       if (EModel::MercedesBencEW213 == model) return "W213";
       if (EModel::MercedesBencSW140 == model) return "W140";
       if (EModel::MercedesBencSW220 == model) return "W220";
       if (EModel::MercedesBencSW221 == model) return "W221";
       if (EModel::MercedesBencSW222 == model) return "W222";
       if (EModel::MercedesBencSW223 == model) return "W223";
       if (EModel::MercedesBencCLC140 == model) return "C140";
       if (EModel::MercedesBencCLC215 == model) return "C215";
       if (EModel::MercedesBencCLC216 == model) return "C216";
       if (EModel::MercedesBencCLAC117 == model) return "C117";
       if (EModel::MercedesBencCLKC208 == model) return "C208";
       if (EModel::MercedesBencCLKA208 == model) return "A208";
       if (EModel::MercedesBencCLKC209 == model) return "C209";
       if (EModel::MercedesBencCLKA209 == model) return "A209";
       if (EModel::MercedesBencCLSC219 == model) return "C219";
       if (EModel::MercedesBencCLSC256 == model) return "C256";
       if (EModel::MercedesBencMLW163 == model) return "W163";
       if (EModel::MercedesBencMLW164 == model) return "W164";
       if (EModel::MercedesBencMLW166 == model) return "W166";
       if (EModel::MercedesBencMLW167 == model) return "W167";
       if (EModel::MercedesBencGW463 == model) return "W463";
       if (EModel::MercedesBencGLX164 == model) return "X164";
       if (EModel::MercedesBencGLX166 == model) return "X166";
       if (EModel::MercedesBencGLAX156 == model) return "X156";
       if (EModel::MercedesBencGLAH247 == model) return "H247";
       if (EModel::MercedesBencGLCX253 == model) return "X253";
       if (EModel::MercedesBencGLCC253 == model) return "C253";
       if (EModel::MercedesBencGLEV167 == model) return "V167";
       if (EModel::MercedesBencGLKX204 == model) return "X204";
       if (EModel::MercedesBencGLSX167 == model) return "X167";
       if (EModel::MercedesBencRW251 == model) return "W251";
       if (EModel::MercedesBencSLR230 == model) return "R230";
       if (EModel::MercedesBencSLR231 == model) return "R231";
       if (EModel::MercedesBencSLKR170 == model) return "R170";
       if (EModel::MercedesBencSLKR171 == model) return "R171";
       if (EModel::MercedesBencSLKR172 == model) return "R172";
       if (EModel::MercedesBencVW638 == model) return "W638";
       if (EModel::MercedesBencVW639 == model) return "W639";
       if (EModel::MercedesBencVW447 == model) return "W447";
       if (EModel::MercedesBencSprinterW901 == model) return "W901";
       if (EModel::MercedesBencSprinterW905 == model) return "W905";
       if (EModel::MercedesBencSprinternNCV3 == model) return "NCV3";
       if (EModel::MercedesBencVaneoW414 == model) return "W414";
       if (EModel::MercedesBencViano == model) return "";
       if (EModel::MercedesBencVito == model) return "VITO";
       if (EModel::AudiA38L == model) return "A38L";
       if (EModel::AudiA38P == model) return "A38P";
       if (EModel::AudiA38V == model) return "A38V";
       if (EModel::AudiA38Y == model) return "A38Y";
       if (EModel::AudiA4B5 == model) return "B5";
       if (EModel::AudiA4B6 == model) return "B6";
       if (EModel::AudiA4B7 == model) return "B7";
       if (EModel::AudiA4B8 == model) return "B8";
       if (EModel::AudiA4B9 == model) return "B9";
       if (EModel::AudiA58T == model) return "8T";
       if (EModel::AudiA5F5 == model) return "F5";
       if (EModel::AudiA6C5 == model) return "C5";
       if (EModel::AudiA6C6 == model) return "C6";
       if (EModel::AudiA6C7 == model) return "C7";
       if (EModel::AudiA6C8 == model) return "C8";
       if (EModel::AudiA7G4 == model) return "G4";
       if (EModel::AudiA74K == model) return "4K";
       if (EModel::AudiA8D2 == model) return "D2";
       if (EModel::AudiA8D3 == model) return "D3";
       if (EModel::AudiA8D4 == model) return "D4";
       if (EModel::AudiA8D5 == model) return "D5";
       if (EModel::AudiQ58R == model) return "8R";
       if (EModel::AudiQ5FY == model) return "FY";
       if (EModel::AudiQ74L == model) return "4L";
       if (EModel::AudiQ74M == model) return "4M";
       if (EModel::AudiTT8N == model) return "8N";
       if (EModel::AudiTT8J == model) return "8J";
       if (EModel::AudiTT8S == model) return "8S";
       if (EModel::PorscheCayenne1 == model) return "1";
       if (EModel::PorscheCayenne2 == model) return "2";
       if (EModel::PorscheCayenne3 == model) return "3";
       if (EModel::PorscheMacan1 == model) return "";
       if (EModel::PorschePanamera1 == model) return "1";
       if (EModel::PorschePanamera2 == model) return "2";
       if (EModel::LexusCT1 == model) return "";
       if (EModel::LexusIS1 == model) return "1";
       if (EModel::LexusIS2 == model) return "2";
       if (EModel::LexusIS3 == model) return "3";
       if (EModel::LexusES4 == model) return "4";
       if (EModel::LexusES5 == model) return "5";
       if (EModel::LexusES6 == model) return "6";
       if (EModel::LexusES7 == model) return "7";
       if (EModel::LexusGS2 == model) return "2";
       if (EModel::LexusGS3 == model) return "3";
       if (EModel::LexusGS4 == model) return "4";
       if (EModel::LexusLS4 == model) return "4";
       if (EModel::LexusLS5 == model) return "5";
       if (EModel::LexusNX1 == model) return "1";
       if (EModel::LexusNX2 == model) return "2";
       if (EModel::LexusRX1 == model) return "1";
       if (EModel::LexusRX2 == model) return "2";
       if (EModel::LexusRX3 == model) return "3";
       if (EModel::LexusRX4 == model) return "4";
       if (EModel::LexusGX1 == model) return "1";
       if (EModel::LexusGX2 == model) return "2";
       if (EModel::LexusLX2 == model) return "2";
       if (EModel::LexusLX3 == model) return "3";
       if (EModel::InfinitiEX1J50 == model) return "1J50";
       if (EModel::InfinitiJX1 == model) return "1";
       if (EModel::InfinitiFX1S50 == model) return "1S50";
       if (EModel::InfinitiFX2S51 == model) return "2S51";
       if (EModel::InfinitiG3 == model) return "3";
       if (EModel::InfinitiG4 == model) return "4";
       if (EModel::InfinitiM3 == model) return "3";
       if (EModel::InfinitiM4 == model) return "4";
       if (EModel::InfinitiQ3 == model) return "3";
       if (EModel::InfinitiQX4 == model) return "";
       if (EModel::InfinitiQX501 == model) return "1";
       if (EModel::InfinitiQX502 == model) return "2";
       if (EModel::InfinitiQX561 == model) return "1";
       if (EModel::InfinitiQX562 == model) return "2";
       if (EModel::InfinitiQX601 == model) return "";
       if (EModel::InfinitiQX70 == model) return "";
       if (EModel::InfinitiQX801 == model) return "1";
       if (EModel::InfinitiQX802 == model) return "2";
       if (EModel::ToyotaAlphard1 == model) return "1";
       if (EModel::ToyotaAlphard2 == model) return "2";
       if (EModel::ToyotaAlphard3 == model) return "3";
       if (EModel::ToyotaAltezza == model) return "";
       if (EModel::ToyotaAvalon3 == model) return "3";
       if (EModel::ToyotaAvalon4 == model) return "4";
       if (EModel::ToyotaAvalon5 == model) return "5";
       if (EModel::ToyotaAvensis2 == model) return "2";
       if (EModel::ToyotaAvensis3 == model) return "3";
       if (EModel::ToyotaBelta == model) return "";
       if (EModel::ToyotaBlade1E150 == model) return "E150";
       if (EModel::ToyotaCHR1 == model) return "1";
       if (EModel::ToyotaCamryXV40 == model) return "XV40";
       if (EModel::ToyotaCamryXV50 == model) return "XV50";
       if (EModel::ToyotaCamryXV70 == model) return "XV70";
       if (EModel::ToyotaCorollaE140 == model) return "E140";
       if (EModel::ToyotaCorollaE160 == model) return "E160";
       if (EModel::ToyotaCorollaE210 == model) return "E210";
       if (EModel::ToyotaEstima2 == model) return "2";
       if (EModel::ToyotaEstima3 == model) return "3";
       if (EModel::ToyotaFJCruiser == model) return "";
       if (EModel::ToyotaFortuner1 == model) return "1";
       if (EModel::ToyotaFortuner2 == model) return "2";
       if (EModel::ToyotaHarrierXU10 == model) return "XU10";
       if (EModel::ToyotaHarrierXU30 == model) return "XU30";
       if (EModel::ToyotaHarrierXU60 == model) return "XU60";
       if (EModel::ToyotaHighlanderU20 == model) return "U20";
       if (EModel::ToyotaHighlanderU40 == model) return "U40";
       if (EModel::ToyotaHighlanderU50 == model) return "U50";
       if (EModel::ToyotaHighlanderU70 == model) return "U70";
       if (EModel::ToyotaHilux6 == model) return "6";
       if (EModel::ToyotaHilux7 == model) return "7";
       if (EModel::ToyotaHilux8 == model) return "8";
       if (EModel::ToyotaIpsumM10 == model) return "M10";
       if (EModel::ToyotaIpsumM20 == model) return "M20";
       if (EModel::ToyotaIst1 == model) return "1";
       if (EModel::ToyotaIst2 == model) return "2";
       if (EModel::ToyotaLandCruiser100 == model) return "100";
       if (EModel::ToyotaLandCruiser200 == model) return "200";
       if (EModel::ToyotaLandCruiser300 == model) return "300";
       if (EModel::ToyotaLandCruiserPrado120 == model) return "120";
       if (EModel::ToyotaLandCruiserPrado150 == model) return "150";
       if (EModel::ToyotaNoahR60 == model) return "R60";
       if (EModel::ToyotaNoahR70 == model) return "R70";
       if (EModel::ToyotaNoahR80 == model) return "R80";
       if (EModel::ToyotaPasso1 == model) return "1";
       if (EModel::ToyotaPasso2 == model) return "2";
       if (EModel::ToyotaPasso3 == model) return "3";
       if (EModel::ToyotaPriusXW10 == model) return "XW10";
       if (EModel::ToyotaPriusXW20 == model) return "XW20";
       if (EModel::ToyotaPriusXW30 == model) return "XW30";
       if (EModel::ToyotaPriusXW50 == model) return "XW50";
       if (EModel::ToyotaRAV4XA10 == model) return "XA10";
       if (EModel::ToyotaRAV4XA20 == model) return "XA20";
       if (EModel::ToyotaRAV4XA30 == model) return "XA30";
       if (EModel::ToyotaRAV4CA40 == model) return "CA40";
       if (EModel::ToyotaRAV4XA50 == model) return "XA50";
       if (EModel::ToyotaSequoia1 == model) return "1";
       if (EModel::ToyotaSequoia2 == model) return "2";
       if (EModel::ToyotaSienna1 == model) return "1";
       if (EModel::ToyotaSienna2 == model) return "2";
       if (EModel::ToyotaSienna3 == model) return "3";
       if (EModel::ToyotaSienna4 == model) return "4";
       if (EModel::ToyotaTacoma1 == model) return "1";
       if (EModel::ToyotaTacoma2 == model) return "2";
       if (EModel::ToyotaTacoma3 == model) return "3";
       if (EModel::ToyotaTundra1 == model) return "1";
       if (EModel::ToyotaTundra2 == model) return "2";
       if (EModel::ToyotaVellfire1 == model) return "1";
       if (EModel::ToyotaVellfire2 == model) return "2";
       if (EModel::ToyotaVitzP10 == model) return "P10";
       if (EModel::ToyotaVitzXP90 == model) return "XP90";
       if (EModel::ToyotaVitzXP130 == model) return "XP130";
       if (EModel::ToyotaVoxyR60 == model) return "R60";
       if (EModel::ToyotaVoxyR70 == model) return "R70";
       if (EModel::ToyotaVoxyR80 == model) return "R80";
       if (EModel::ToyotaYaris == model) return "";
       if (EModel::NissanAlmeraN16 == model) return "N16";
       if (EModel::NissanAlmeraG15 == model) return "G15";
       if (EModel::NissanAltimaL32 == model) return "L32";
       if (EModel::NissanAltimaL33 == model) return "L33";
       if (EModel::NissanAltimaL34 == model) return "L34";
       if (EModel::NissanArmada1 == model) return "1";
       if (EModel::NissanArmada2 == model) return "2";
       if (EModel::NissanBluebird == model) return "";
       if (EModel::NissanCubeZ10 == model) return "Z10";
       if (EModel::NissanCubeZ11 == model) return "Z11";
       if (EModel::NissanCubeZ12 == model) return "Z12";
       if (EModel::NissanElgrandE50 == model) return "E50";
       if (EModel::NissanElgrandE51 == model) return "E51";
       if (EModel::NissanElgrandE52 == model) return "E52";
       if (EModel::NissanFrontier == model) return "";
       if (EModel::NissanFuga1 == model) return "1";
       if (EModel::NissanFuga2 == model) return "2";
       if (EModel::NissanJuke1 == model) return "1";
       if (EModel::NissanJuke2 == model) return "2";
       if (EModel::NissanKicks1 == model) return "";
       if (EModel::NissanLatioN71 == model) return "N71";
       if (EModel::NissanLeafZE0 == model) return "ZE0";
       if (EModel::NissanLeafZE1 == model) return "ZE1";
       if (EModel::NissanMarchK12 == model) return "K12";
       if (EModel::NissanMarchK13 == model) return "K13";
       if (EModel::NissanMaximaA34 == model) return "A34";
       if (EModel::NissanMaximaA35 == model) return "A35";
       if (EModel::NissanMaximaA36 == model) return "A36";
       if (EModel::NissanMicra3 == model) return "3";
       if (EModel::NissanMicra4 == model) return "4";
       if (EModel::NissanMicra5 == model) return "5";
       if (EModel::NissanMuranoZ50 == model) return "Z50";
       if (EModel::NissanMuranoZ51 == model) return "Z51";
       if (EModel::NissanMuranoZ52 == model) return "Z52";
       if (EModel::NissanNote1 == model) return "1";
       if (EModel::NissanNote2 == model) return "2";
       if (EModel::NissanPathfinder3 == model) return "3";
       if (EModel::NissanPathfinder4 == model) return "4";
       if (EModel::NissanPathfinder5 == model) return "5";
       if (EModel::NissanPatrolY61 == model) return "Y61";
       if (EModel::NissanPatrolY62 == model) return "Y62";
       if (EModel::NissanPresage1 == model) return "1";
       if (EModel::NissanPresage2 == model) return "2";
       if (EModel::NissanQashqai1 == model) return "1";
       if (EModel::NissanQashqai2 == model) return "2";
       if (EModel::NissanQashqai3 == model) return "3";
       if (EModel::NissanQuest3 == model) return "3";
       if (EModel::NissanQuest4 == model) return "4";
       if (EModel::NissanRogue1 == model) return "1";
       if (EModel::NissanRogue2 == model) return "2";
       if (EModel::NissanRogue3 == model) return "3";
       if (EModel::NissanSentraB16 == model) return "B16";
       if (EModel::NissanSentraB17 == model) return "B17";
       if (EModel::NissanSentraB18 == model) return "B18";
       if (EModel::NissanSerenaC24 == model) return "C24";
       if (EModel::NissanSerenaC25 == model) return "C25";
       if (EModel::NissanSerenaC26 == model) return "C26";
       if (EModel::NissanSerenaC27 == model) return "C27";
       if (EModel::NissanSkylineR34 == model) return "R34";
       if (EModel::NissanSkylineV35 == model) return "V35";
       if (EModel::NissanSkylineV36 == model) return "V36";
       if (EModel::NissanSkylineV37 == model) return "V37";
       if (EModel::NissanSunnyN16 == model) return "N16";
       if (EModel::NissanSunnyB10 == model) return "B10";
       if (EModel::NissanTeana1 == model) return "1";
       if (EModel::NissanTeana2 == model) return "2";
       if (EModel::NissanTeana3 == model) return "3";
       if (EModel::NissanTerrano2 == model) return "2";
       if (EModel::NissanTerrano3 == model) return "3";
       if (EModel::NissanTiida1 == model) return "1";
       if (EModel::NissanTiida2 == model) return "2";
       if (EModel::NissanVersa1 == model) return "1";
       if (EModel::NissanVersa2 == model) return "2";
       if (EModel::NissanVersa3 == model) return "3";
       if (EModel::NissanXTrail1 == model) return "1";
       if (EModel::NissanXTrail2 == model) return "2";
       if (EModel::NissanXTrail3 == model) return "3";
       if (EModel::NissanXTerra1 == model) return "1";
       if (EModel::NissanXTerra2 == model) return "2";
       if (EModel::Nissan350Z == model) return "";
       if (EModel::FordEdge1 == model) return "1";
       if (EModel::FordEdge2 == model) return "2";
       if (EModel::FordEscape1 == model) return "1";
       if (EModel::FordEscape2 == model) return "2";
       if (EModel::FordEscape3 == model) return "3";
       if (EModel::FordEscape4 == model) return "4";
       if (EModel::FordExplorer1 == model) return "1";
       if (EModel::FordExplorer2 == model) return "2";
       if (EModel::FordExplorer3 == model) return "3";
       if (EModel::FordExplorer4 == model) return "4";
       if (EModel::FordExplorer5 == model) return "5";
       if (EModel::FordExplorer6 == model) return "6";
       if (EModel::FordF15010 == model) return "10";
       if (EModel::FordF15011 == model) return "11";
       if (EModel::FordF15012 == model) return "12";
       if (EModel::FordF15013 == model) return "13";
       if (EModel::FordFiestaMK6 == model) return "MK6";
       if (EModel::FordFiestaMK7 == model) return "MK7";
       if (EModel::FordFocus1 == model) return "1";
       if (EModel::FordFocus2 == model) return "2";
       if (EModel::FordFocus3 == model) return "3";
       if (EModel::FordFocus4 == model) return "4";
       if (EModel::FordFusion2 == model) return "2";
       if (EModel::FordTaurus6 == model) return "6";
       if (EModel::FordTransit == model) return "";
       if (EModel::FordMustang4 == model) return "4";
       if (EModel::FordMustang5 == model) return "5";
       if (EModel::FordMustang6 == model) return "6";
       if (EModel::ChevroletAvalanche1 == model) return "1";
       if (EModel::ChevroletAvalanche2 == model) return "2";
       if (EModel::ChevroletAveo1 == model) return "1";
       if (EModel::ChevroletAveo2 == model) return "2";
       if (EModel::ChevroletAveo3 == model) return "3";
       if (EModel::ChevroletCaptiva1 == model) return "1";
       if (EModel::ChevroletCruze1 == model) return "1";
       if (EModel::ChevroletCruze2 == model) return "2";
       if (EModel::ChevroletEpicaV250 == model) return "V250";
       if (EModel::ChevroletEquinox1 == model) return "1";
       if (EModel::ChevroletEquinox2 == model) return "2";
       if (EModel::ChevroletEquinox3 == model) return "3";
       if (EModel::ChevroletMalibu7 == model) return "7";
       if (EModel::ChevroletMalibu8 == model) return "8";
       if (EModel::ChevroletMalibu9 == model) return "9";
       if (EModel::ChevroletNiva == model) return "";
       if (EModel::ChevroletTahoe2 == model) return "2";
       if (EModel::ChevroletTahoe3 == model) return "3";
       if (EModel::ChevroletTahoe4 == model) return "4";
       if (EModel::ChevroletTahoe5 == model) return "5";
       if (EModel::ChevroletTrailBlazer1 == model) return "1";
       if (EModel::ChevroletTrailBlazer2 == model) return "2";
       if (EModel::ChevroletTrailBlazer3 == model) return "3";
       if (EModel::ChevroletVolt1 == model) return "1";
       if (EModel::ChevroletVolt2 == model) return "2";
       if (EModel::ChevroletCamaro5 == model) return "5";
       if (EModel::ChevroletCamaro6 == model) return "6";
       if (EModel::ChevroletCorvette == model) return "";
       if (EModel::VolkswagenBeetleA4 == model) return "A4";
       if (EModel::VolkswagenBeetleA5 == model) return "A5";
       if (EModel::VolkswagenBora1998 == model) return "1998";
       if (EModel::VolkswagenBora4 == model) return "4";
       if (EModel::VolkswagenCaddy2 == model) return "2";
       if (EModel::VolkswagenCaddy3 == model) return "3";
       if (EModel::VolkswagenCaddy4 == model) return "4";
       if (EModel::VolkswagenCaddy5 == model) return "5";
       if (EModel::VolkswagenCrafter == model) return "";
       if (EModel::VolkswagenGolf2 == model) return "2";
       if (EModel::VolkswagenGolf3 == model) return "3";
       if (EModel::VolkswagenGolf4 == model) return "4";
       if (EModel::VolkswagenGolf5 == model) return "5";
       if (EModel::VolkswagenGolf6 == model) return "6";
       if (EModel::VolkswagenGolf7 == model) return "7";
       if (EModel::VolkswagenGolf8 == model) return "8";
       if (EModel::VolkswagenJetta3 == model) return "3";
       if (EModel::VolkswagenJetta4 == model) return "4";
       if (EModel::VolkswagenJetta5 == model) return "5";
       if (EModel::VolkswagenJetta6 == model) return "6";
       if (EModel::VolkswagenJetta7 == model) return "7";
       if (EModel::VolkswagenPassatB5 == model) return "B5";
       if (EModel::VolkswagenPassatB6 == model) return "B6";
       if (EModel::VolkswagenPassatB7 == model) return "B7";
       if (EModel::VolkswagenPassatB8 == model) return "B8";
       if (EModel::VolkswagenPassatCC1 == model) return "";
       if (EModel::VolkswagenPolo3 == model) return "3";
       if (EModel::VolkswagenPolo4 == model) return "4";
       if (EModel::VolkswagenPolo5 == model) return "5";
       if (EModel::VolkswagenPolo6 == model) return "6";
       if (EModel::VolkswagenRoutan == model) return "";
       if (EModel::VolkswagenTiguan1 == model) return "1";
       if (EModel::VolkswagenTiguan2 == model) return "2";
       if (EModel::VolkswagenTouareg1 == model) return "1";
       if (EModel::VolkswagenTouareg2 == model) return "2";
       if (EModel::VolkswagenTouareg3 == model) return "3";
       if (EModel::VolkswagenTouran1 == model) return "1";
       if (EModel::VolkswagenTouran2 == model) return "2";
       if (EModel::VolkswagenTouran3 == model) return "3";
       if (EModel::VolkswagenTransporterT4 == model) return "T4";
       if (EModel::VolkswagenTransporterT5 == model) return "T5";
       if (EModel::VolkswagenTransporterT6 == model) return "T6";
       if (EModel::VolkswagenVento == model) return "";
       if (EModel::OpelAstraF == model) return "F";
       if (EModel::OpelAstraG == model) return "G";
       if (EModel::OpelAstraH == model) return "H";
       if (EModel::OpelAstraJ == model) return "J";
       if (EModel::OpelAstraK == model) return "K";
       if (EModel::OpelComboC == model) return "C";
       if (EModel::OpelComboD == model) return "D";
       if (EModel::OpelComboE == model) return "E";
       if (EModel::OpelComboPCMA == model) return "PCMA";
       if (EModel::OpelCorsaA == model) return "A";
       if (EModel::OpelCorsaB == model) return "B";
       if (EModel::OpelCorsaC == model) return "C";
       if (EModel::OpelCorsaD == model) return "D";
       if (EModel::OpelCorsaE == model) return "E";
       if (EModel::OpelCorsaF == model) return "F";
       if (EModel::OpelFronteraA == model) return "A";
       if (EModel::OpelFronteraB == model) return "B";
       if (EModel::OpelInsignia1 == model) return "1";
       if (EModel::OpelInsignia2 == model) return "2";
       if (EModel::OpelMerivaA == model) return "A";
       if (EModel::OpelMerivaB == model) return "B";
       if (EModel::OpelOmegaA == model) return "A";
       if (EModel::OpelOmegaB == model) return "B";
       if (EModel::OpelSignum == model) return "";
       if (EModel::OpelSintra == model) return "";
       if (EModel::OpelVectraA == model) return "A";
       if (EModel::OpelVectraB == model) return "B";
       if (EModel::OpelVectraC == model) return "C";
       if (EModel::OpelZafiraA == model) return "A";
       if (EModel::OpelZafiraB == model) return "B";
       if (EModel::OpelZafiraC == model) return "C";
       if (EModel::MitsubishiAirtrek == model) return "";
       if (EModel::MitsubishiChariot2 == model) return "2";
       if (EModel::MitsubishiChariot3 == model) return "3";
       if (EModel::MitsubishiColtZ30 == model) return "Z30";
       if (EModel::MitsubishiGalant8 == model) return "8";
       if (EModel::MitsubishiGalant9 == model) return "9";
       if (EModel::MitsubishiGrandis == model) return "";
       if (EModel::MitsubishiLancer9 == model) return "9";
       if (EModel::MitsubishiLancer10 == model) return "10";
       if (EModel::MitsubishiMontero3 == model) return "3";
       if (EModel::MitsubishiMontero4 == model) return "4";
       if (EModel::MitsubishiOutlander1 == model) return "1";
       if (EModel::MitsubishiOutlander2 == model) return "2";
       if (EModel::MitsubishiOutlander3 == model) return "3";
       if (EModel::MitsubishiPajero2 == model) return "2";
       if (EModel::MitsubishiPajero3 == model) return "3";
       if (EModel::MitsubishiPajero4 == model) return "4";
       if (EModel::KIACadenza1 == model) return "1";
       if (EModel::KIACadenza2 == model) return "2";
       if (EModel::KIACerato1 == model) return "1";
       if (EModel::KIACerato2 == model) return "2";
       if (EModel::KIACerato3 == model) return "3";
       if (EModel::KIAForte1 == model) return "1";
       if (EModel::KIAForte2 == model) return "2";
       if (EModel::KIAForte3 == model) return "3";
       if (EModel::KIAK51 == model) return "1";
       if (EModel::KIAK52 == model) return "2";
       if (EModel::KIAK53 == model) return "3";
       if (EModel::KIAOptima2 == model) return "2";
       if (EModel::KIAOptima3 == model) return "3";
       if (EModel::KIAOptima4 == model) return "4";
       if (EModel::KIARio2 == model) return "2";
       if (EModel::KIARio3 == model) return "3";
       if (EModel::KIARio4 == model) return "4";
       if (EModel::KIASedona1 == model) return "1";
       if (EModel::KIASedona2 == model) return "2";
       if (EModel::KIASedona3 == model) return "3";
       if (EModel::KIASorento1 == model) return "1";
       if (EModel::KIASorento2 == model) return "2";
       if (EModel::KIASorento3 == model) return "3";
       if (EModel::KIASorento4 == model) return "4";
       if (EModel::KIASportage2 == model) return "2";
       if (EModel::KIASportage3 == model) return "3";
       if (EModel::KIASportage4 == model) return "4";
       if (EModel::HyundaiAccent2 == model) return "2";
       if (EModel::HyundaiAccent3 == model) return "3";
       if (EModel::HyundaiAccent4 == model) return "4";
       if (EModel::HyundaiAccent5 == model) return "5";
       if (EModel::HyundaiCreta1 == model) return "1";
       if (EModel::HyundaiCreta2 == model) return "2";
       if (EModel::HyundaiElantra4 == model) return "4";
       if (EModel::HyundaiElantra5 == model) return "5";
       if (EModel::HyundaiElantra6 == model) return "6";
       if (EModel::HyundaiElantra7 == model) return "7";
       if (EModel::HyundaiGenesis1 == model) return "1";
       if (EModel::HyundaiGenesis2 == model) return "2";
       if (EModel::HyundaiGenesisCoupe1 == model) return "";
       if (EModel::HyundaiIX351 == model) return "";
       if (EModel::HyundaiKona1 == model) return "";
       if (EModel::HyundaiSantaFe1 == model) return "1";
       if (EModel::HyundaiSantaFe2 == model) return "2";
       if (EModel::HyundaiSantaFe3 == model) return "3";
       if (EModel::HyundaiSantaFe4 == model) return "4";
       if (EModel::HyundaiSolaris1 == model) return "1";
       if (EModel::HyundaiSolaris2 == model) return "2";
       if (EModel::HyundaiSonata5 == model) return "5";
       if (EModel::HyundaiSonata6 == model) return "6";
       if (EModel::HyundaiSonata7 == model) return "7";
       if (EModel::HyundaiSonata8 == model) return "8";
       if (EModel::HyundaiTucson1 == model) return "1";
       if (EModel::HyundaiTucson2 == model) return "2";
       if (EModel::HyundaiTucson3 == model) return "3";
       if (EModel::HyundaiTucson4 == model) return "4";
       if (EModel::HyundaiVeloster1 == model) return "1";
       if (EModel::HyundaiVeloster2 == model) return "2";
       if (EModel::HondaAccord7 == model) return "7";
       if (EModel::HondaAccord8 == model) return "8";
       if (EModel::HondaAccord9 == model) return "9";
       if (EModel::HondaAccord10 == model) return "10";
       if (EModel::HondaCivic7 == model) return "7";
       if (EModel::HondaCivic8 == model) return "8";
       if (EModel::HondaCivic9 == model) return "9";
       if (EModel::HondaCivic10 == model) return "10";
       if (EModel::HondaCivic11 == model) return "11";
       if (EModel::HondaCRV1 == model) return "1";
       if (EModel::HondaCRV2 == model) return "2";
       if (EModel::HondaCRV3 == model) return "3";
       if (EModel::HondaCRV4 == model) return "4";
       if (EModel::HondaCRV5 == model) return "5";
       if (EModel::HondaCrosstour1 == model) return "";
       if (EModel::HondaElysion1 == model) return "1";
       if (EModel::HondaFit1 == model) return "1";
       if (EModel::HondaFit2 == model) return "2";
       if (EModel::HondaFit3 == model) return "3";
       if (EModel::HondaHRV1 == model) return "1";
       if (EModel::HondaHRV2 == model) return "2";
       if (EModel::HondaOdyssey3 == model) return "3";
       if (EModel::HondaOdyssey4 == model) return "4";
       if (EModel::HondaOdyssey5 == model) return "5";
       if (EModel::HondaOdyssey6 == model) return "6";
       if (EModel::HondaPilot1 == model) return "1";
       if (EModel::HondaPilot2 == model) return "2";
       if (EModel::HondaPilot3 == model) return "3";
       if (EModel::HondaRidgeline1 == model) return "1";
       if (EModel::HondaRidgeline2 == model) return "2";
       if (EModel::HondaStepwgn2 == model) return "2";
       if (EModel::HondaStepwgn3 == model) return "3";
       if (EModel::HondaStepwgn4 == model) return "4";
       if (EModel::HondaStepwgn5 == model) return "5";
       if (EModel::MazdaAtenza1 == model) return "1";
       if (EModel::MazdaAtenza2 == model) return "2";
       if (EModel::MazdaAtenza3 == model) return "3";
       if (EModel::MazdaCX31 == model) return "";
       if (EModel::MazdaCX51 == model) return "1";
       if (EModel::MazdaCX52 == model) return "2";
       if (EModel::MazdaCX71 == model) return "";
       if (EModel::MazdaCX91 == model) return "1";
       if (EModel::MazdaCX92 == model) return "2";
       if (EModel::MazdaDemio1 == model) return "1";
       if (EModel::MazdaDemio2 == model) return "2";
       if (EModel::MazdaDemio3 == model) return "3";
       if (EModel::MazdaDemio4 == model) return "4";
       if (EModel::MazdaMPV2 == model) return "2";
       if (EModel::MazdaMPV3 == model) return "3";
       if (EModel::MazdaRX8 == model) return "";
       if (EModel::MazdaTribute1 == model) return "1";
       if (EModel::MazdaTribute2 == model) return "2";
       if (EModel::Mazda32 == model) return "2";
       if (EModel::Mazda33 == model) return "3";
       if (EModel::Mazda34 == model) return "4";
       if (EModel::Mazda51 == model) return "1";
       if (EModel::Mazda52 == model) return "2";
       if (EModel::Mazda61 == model) return "1";
       if (EModel::Mazda62 == model) return "2";
       if (EModel::Mazda63 == model) return "3";
       return "";
   }
};

#endif
